### ISSUE TITLE
⚠️ Linter make warn and error all over the places

### ISSUE THREAD

**Issue by PH9** [atikom17315/Github-Repo#2]
# WHAT

Linter make warn and error all over the places.

# WHY

Because my Xcode was set derived data directory to related with project path. 

| Settings | Result |
| --- | --- |
| ![Screen Shot 2564-03-27 at 07 45 34](https://user-images.githubusercontent.com/6365973/112705234-6b54e680-8ed0-11eb-8b56-a5eee660fbe6.png) | ![Screen Shot 2564-03-27 at 08 00 43](https://user-images.githubusercontent.com/6365973/112705724-9b04ee00-8ed2-11eb-9a4f-71b9558d54e9.png) |

# HOW TO FIX

There are 2 ways

1 I need to change the derived data directory back to Xcode default.
2 Supporting in `.swiftlint.yml` to exclude `DerivedData`

It would be nice for me if we go with the seconds way. But I still have a question. Where location should it be in the `.swiftlint.yml` file. In another way, `DerivedData` is already in `.gitignore` file at the root of the repository.

# QUESRTION for next PR

For now, it is like the following sample code.

```
1 disabled_rules
2 custom configurations
```

For normal I am using disabled and excluded with be at the very bottom of the file. And in my style, will be like below.

```
1 custom configurations
2 opt_in_rules
3 custom rules
4 excluded
5 disabled_rules
6 reporter
```

What do you suggest if you allow this project to support the Local DerivedData path? And which places it should be for `excluded` in `.swiftlint.yml`?.

**Comment by PH9** [comment]
Other things `.swiftlint.yml` is also not exclude `Pods` directory shall we ignore it also?

**Comment by atikomtancharoen** [comment]
> Other things `.swiftlint.yml` is also not exclude `Pods` directory shall we ignore it also?

Sorry, I will add this code to `.swiftlint.yml`
```
excluded:
- Carthage
- Pods
```

**Comment by atikomtancharoen** [comment]
> # WHAT
> Linter make warn and error all over the places.
> 
> # WHY
> Because my Xcode was set derived data directory to related with project path.
> 
> Settings	Result
> ![Screen Shot 2564-03-27 at 07 45 34](https://user-images.githubusercontent.com/6365973/112705234-6b54e680-8ed0-11eb-8b56-a5eee660fbe6.png)	![Screen Shot 2564-03-27 at 08 00 43](https://user-images.githubusercontent.com/6365973/112705724-9b04ee00-8ed2-11eb-9a4f-71b9558d54e9.png)
> # HOW TO FIX
> There are 2 ways
> 
> 1 I need to change the derived data directory back to Xcode default.
> 2 Supporting in `.swiftlint.yml` to exclude `DerivedData`
> 
> It would be nice for me if we go with the seconds way. But I still have a question. Where location should it be in the `.swiftlint.yml` file. In another way, `DerivedData` is already in `.gitignore` file at the root of the repository.
> 
> # QUESRTION for next PR
> For now, it is like the following sample code.
> 
> ```
> 1 disabled_rules
> 2 custom configurations
> ```
> 
> For normal I am using disabled and excluded with be at the very bottom of the file. And in my style, will be like below.
> 
> ```
> 1 custom configurations
> 2 opt_in_rules
> 3 custom rules
> 4 excluded
> 5 disabled_rules
> 6 reporter
> ```
> 
> What do you suggest if you allow this project to support the Local DerivedData path? And which places it should be for `excluded` in `.swiftlint.yml`?.

I have a question, you use the Local DerivedData path for CI, Am I right?

**Comment by PH9** [comment]
Yeah, on both ci and my machine. It is easier for me to remove DerivedData directory when I want.

**Comment by atikomtancharoen** [comment]
[issue-842379000](https://github.com/atikom17315/Github-Repo/issues/2#issue-842379000)
From the second way, I'm not sure about the question. do you need to add the DerivedData path to `excluded` in `.swiftlint.yml`, Am I right?

**Comment by PH9** [comment]
Yes, that what I mean.

**Comment by atikomtancharoen** [comment]
Ok, I see. So I will add it krub.

**Comment by atikomtancharoen** [comment]
Done!
